### ISSUE TITLE
Error: EGeneral:Unknown method

### ISSUE THREAD

**Issue by bogorad** [redbtc/node-red-contrib-kraken#21]
Suddenly Kraken started returning

`Error: EGeneral:Unknown method` 

Tried creating a new key - didn't help.

**Comment by bogorad** [comment]
```
Error: EGeneral:Unknown method
    at KrakenClient.makeRequest (/data/node_modules/node-red-contrib-kraken/dist/nodes/kraken-api-config/modules/kraken-client.js:29:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async KrakenClient.publicRequest (/data/node_modules/node-red-contrib-kraken/dist/nodes/kraken-api-config/modules/kraken-client.js:37:16)
    at async KrakenApiNodeConstructor._inputCallback (/data/node_modules/node-red-contrib-kraken/dist/nodes/kraken-api/kraken-api.js:39:33)
```

**Comment by bogorad** [comment]
Never mind, probably a bug on Kraken's side, fixed now.
